### ISSUE TITLE
Marathon support

### ISSUE THREAD

**Issue by stevendborrelli** [airbnb/nerve#29]
Is there any support for nerve getting port information dynamically from Marathon? 

We are thinking a config item that points to a list of marathon master (or pulls this info from marathon's zk), and a starting list of marathon job ids to monitor. 

Nerve would then query marathon/v1/endpoints and update zk as the jobs are moved around the mesos cluster. Or, it could watch zk marathon/tasks to get the tasks & ports as they are created/deleted.

The use case is using marathon to launch docker containers in mesos, using nerve + synapse for proxy configuration.

**Comment by jolynch** [comment]
Nerve does support marathon, you just have to tell it to start watching the services that mesos has deployed to a slave. We do this with a cron job that updates registrations and SIGHUPs nerve every 5s ([source](https://github.com/Yelp/nerve-tools/blob/master/src/nerve_tools/configure_nerve.py)).

I think that we decided to go the way of change the nerve config and send a SIGHUP rather than nerve dynamically adding and removing watchers. Unix philosophy and such.
